CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  username VARCHAR(20)  UNIQUE NOT NULL , 
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE dataset (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name VARCHAR(50) NOT NULL,
  usr_id INT NOT NULL,
  date_time TIMESTAMP,
  private BOOL NOT NULL,
  FOREIGN KEY (usr_id) REFERENCES users (id),
  PRIMARY KEY (usr_id,name)
);

CREATE TABLE item (
  id INT,
  dataset_id INT,
  FOREIGN KEY (dataset_id) REFERENCES dataset (id),
  PRIMARY KEY (id, dataset_id)
);

CREATE TABLE client (
  id INT,
  dataset_id INT,
  FOREIGN KEY (dataset_id) REFERENCES dataset (id),
  PRIMARY KEY (id, dataset_id)
);

CREATE TABLE interaction (
  dataset_id INT NOT NULL,
  client_id INT NOT NULL,
  item_id INT NOT NULL,
  tmstamp TIMESTAMP NOT NULL,
  PRIMARY KEY (dataset_id,client_id,item_id, tmstamp)
);

CREATE TABLE metadata (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id INT NOT NULL REFERENCES dataset(id)
);

CREATE TABLE metadata_element (
  item_id INT NOT NULL,
  dataset_id INT NOT NULL,
  metadata_id INT NOT NULL REFERENCES metadata (id),
  description TEXT NOT NULL,
  data TEXT NOT NULL,
  FOREIGN KEY (item_id, dataset_id) REFERENCES item(id, dataset_id),
  PRIMARY KEY (item_id, metadata_id, description)
);

CREATE TABLE scenario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name VARCHAR(50) NOT NULL,
  usr_id INT NOT NULL REFERENCES users(id),
  date_time TIMESTAMP,
  dataset_id INT NOT NULL REFERENCES dataset(id),
  sDate TIMESTAMP NOT NULL,
  eDate TIMESTAMP NOT NULL,
  max_items INT NOT NULL,
  min_items INT NOT NULL,
  max_clients INT NOT NULL,
  min_clients INT NOT NULL,
  PRIMARY KEY (usr_id,name)
  );

CREATE TABLE scenario_element (
  scenario_id INTEGER NOT NULL,
  client_id INT NOT NULL,
  item_id INT NOT NULL,
  tmstamp TIMESTAMP NOT NULL,
  PRIMARY KEY (scenario_id, client_id, item_id, tmstamp)
);
 
CREATE TABLE model (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  usr_id INT NOT NULL REFERENCES users(id),
  name VARCHAR (50) NOT NULL,
  algorithm VARCHAR (50) NOT NULL,
  scenario_id INT NOT NULl REFERENCES scenario(id),
  date_time TIMESTAMP NOT NULL,
  parameters VARCHAR[][2] NOT NULL,
  matrix VARBINARY(MAX),
  PRIMARY KEY (usr_id,name)
);


